Repository wecode-bootcamp-korea/31-1st-Dont-SOT-frontend, pull requests merged in 2022-04, with the labels that each got.

#5 [31기 홍두현] add : 상단 nav 작업 완료
  src/Router.js
  src/assets/images/facebook.png
  src/assets/images/insta.png
  src/assets/images/logo-s.png
  src/assets/images/logo2.png
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/components/Nav/navData.js
Labels: Status: Accepted

#8 [31기 이근휘] Add: config.js 파일 생성
  src/config.js
Labels: Status: 리뷰 요청

#4 [31기 홍두현] ADD : 메인 슬라이드 루프, 상품 버튼 슬라이드
  package-lock.json
  public/data/bestData.json
  public/data/slideData.json
  public/images/slide-img01.jpg
  public/images/slide-img02.jpg
  public/images/slide-img03.jpg
  public/images/slide-img04.jpg
  public/images/slide-img05.jpg
  src/assets/images/btn_next.png
  src/assets/images/btn_prev.png
  src/pages/Join/Join.js
  src/pages/Main/ItemList/Best.js
  src/pages/Main/ItemList/best.scss
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
  src/pages/Main/Slide/Slide.js
  src/pages/Main/Slide/slide.scss
Labels: Status: Accepted

#3 [31기 김정수] ADD:공통 컴포넌트 footer
  src/assets/images/footerFace.png
  src/assets/images/footerInsta.png
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
  src/components/Footer/footerLi/footerLi.js
Labels: Status: Accepted

#12 [31기 김정수] ADD:공통 route 수정 route 카트경로 추가 및 footer import
  src/Router.js
Labels: Status: 리뷰 요청

#11 [31기 홍두현] modify : 상단 nav merge 후 레이아웃 깨짐 현상 수정
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
Labels: Status: 리뷰 요청

#13 [31기 김정수] footer - modify: merge후 레이아웃 깨짐 수정
  src/components/Footer/Footer.scss
Labels: Status: 리뷰 요청

#6 [31기 이근휘] ADD : 로그인 페이지 레이아웃 및 로그인 기능구현
  src/assets/images/glasses.png
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
Labels: Status: 리뷰 요청

#10 [31기 김정수] ADD: cart 기본 레이아웃
  package-lock.json
  public/data/cartData.json
  src/pages/Cart/Cart.js
  src/pages/Cart/Cart.scss
  src/pages/Cart/CartItem/CartItem.js
  src/pages/Cart/CartItem/CartItem.scss
Labels: Status: 도움 요청, Status: 추가 기능 구현중, Status: 리뷰 요청

#16 [31기 홍두현] FIX : nav 레이아웃 및 스타일 재설정, 로그인/회원가입 navigate연결
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
Labels: Status: Accepted

#17 [31기 홍두현] modify : 슬라이드 useEffect 의존성 배열 추가
  src/pages/Main/Main.js
Labels: Status: Accepted

#15 [31기 김정수] Modify :공통 컴포넌트 footer 컴포넌트간 보기좋은 간격을 위한 margin-top값 수정
  src/components/Footer/Footer.scss
Labels: Status: Accepted

#18 [31기 김정수] ADD: CART(장바구니) 수량 변경 에따른 총계 / 삭제
  public/data/cartData.json
  src/Router.js
  src/config.js
  src/pages/Cart/Cart.js
  src/pages/Cart/Cart.scss
  src/pages/Cart/CartItem/CartItem.js
  src/pages/Cart/CartItem/CartItem.scss
  src/pages/Cart/CartList/CartList.js
Labels: Status: Accepted

#19 [31기 홍두현] modify : 목데이터 삭제, API 통신 작업 완료
  public/data/bestData.json
  src/config.js
  src/pages/Main/ItemList/Best.js
Labels: Status: Accepted

#20 [31기 이근휘] 로그인 img & hover 기능 추가
  src/assets/images/icon_chb.png
  src/assets/images/search.png
  src/assets/images/search_hover.png
  src/config.js
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
Labels: Status: Accepted

#2 [31기 박경서] 제품 리스트 + 제품 상세 페이지
  public/data/menuData.json
  public/images/fooditem.png
  public/images/hansot.jpeg
  src/Router.js
  src/assets/images/allow.png
  src/assets/images/element.png
  src/assets/images/fooditem.png
  src/assets/images/hansot.jpeg
  src/assets/images/icon_aller.png
  src/assets/images/icon_back.png
  src/config.js
  src/pages/Cart/Cart.js
  src/pages/Menu/Aside/Aside.js
  src/pages/Menu/Components/Aside/Aside.js
  src/pages/Menu/Components/Aside/Aside.scss
  src/pages/Menu/Components/Aside/CategoryList/CategoryList.js
  src/pages/Menu/Components/Aside/CategoryList/CategoryList.scss
  src/pages/Menu/Components/Aside/CategoryList/Item.js
  src/pages/Menu/Components/Aside/CategoryList/Item.scss
  src/pages/Menu/Components/Aside/categoryData.js
  src/pages/Menu/Components/Card/Card.js
  src/pages/Menu/Components/Card/Card.scss
  src/pages/Menu/Components/MenuBox/MenuBox.js
  src/pages/Menu/Components/MenuBox/MenuBox.scss
  src/pages/Menu/Components/ProductSpec/Components/Allergy.js
  src/pages/Menu/Components/ProductSpec/Components/Allergy.scss
  src/pages/Menu/Components/ProductSpec/Components/Country.js
  src/pages/Menu/Components/ProductSpec/Components/Country.scss
  src/pages/Menu/Components/ProductSpec/Components/MenuDetail.js
  src/pages/Menu/Components/ProductSpec/Components/MenuDetail.scss
  src/pages/Menu/Components/ProductSpec/Components/Quantity.js
  src/pages/Menu/Components/ProductSpec/Components/Quantity.scss
  src/pages/Menu/Components/ProductSpec/ProductSpec.js
  src/pages/Menu/Components/ProductSpec/ProductSpec.scss
  src/pages/Menu/Menu.js
  src/pages/Menu/MenuList/MenuList.js
  src/pages/Menu/Products.js
  src/pages/Menu/Products.scss
Labels: Status: 리뷰 요청

#7 [31기 이근휘] Add: Join페이지 레이아웃 및 기능구현
  src/pages/Join/Form/Form.js
  src/pages/Join/Form/FormInputs.js
  src/pages/Join/Form/JoinFormData.js
  src/pages/Join/Join.js
  src/pages/Join/Join.scss
  src/styles/variables.scss
Labels: Status: 리뷰 요청

#21 [31기 이근휘] config.js 수정
  src/config.js
Labels: Status: Accepted

#22 [31기 홍두현] modify : 원산지, 알러지, 열량 API 통신 완료
  src/pages/Menu/Components/ProductSpec/Components/Allergy.js
  src/pages/Menu/Components/ProductSpec/Components/Allergy.scss
  src/pages/Menu/Components/ProductSpec/Components/Country.js
  src/pages/Menu/Components/ProductSpec/Components/Country.scss
  src/pages/Menu/Components/ProductSpec/Components/Quantity.js
  src/pages/Menu/Components/ProductSpec/ProductSpec.js
Labels: Status: Accepted

#24 [31기 이근휘] Modify: navigate 경로 수정 & 불필요한 state 삭제 & className 수정
  src/pages/Join/Join.js
Labels: Status: 리뷰 요청
